### PR TITLE
freenet-ext: Replace ant-contrib conditionals

### PR DESCRIPTION
**Pull request by llamora**
This change removes the ant-contrib style <if><then><else> elements and
uses if:true and unless:true style ant attributes.
These attributes have been available to all tasks and nested elements
since Ant 1.9.1 and require special namespaces.

### CODE REVIEW

**Comment by llamora** [comment]
Because git rebase doesn't work very well with already pushed changes, I re-created the branch to squash the changes locally. This should meet the coding standards and clears up the requests by Thynix (Steve Dougherty)

**Comment by Thynix** [comment]
I regret to report that this causes a regression for me. I'm able to build 60410e1648b2b284bd59f580aaa0a6a4bc90c98c but when I merge this I get

prepare-libsrc:
        [mkdir] Created dir: /home/steve/freenet/contrib/freenet-ext/tmp
        [untar] Expanding: /home/steve/freenet/contrib/freenet-ext/lib/wrapper_3.5.5_src.tar.gz into /home/steve/freenet/contrib/freenet-ext/tmp
         [move] Moving 200 files to /home/steve/freenet/contrib
    Attempt to copy /home/steve/freenet/contrib/freenet-ext/tmp/wrapper_3.5.5_src/doc/index.html to /home/steve/freenet/contrib/wrapper/doc/index.html using NIO Channels failed due to '/home/steve/freenet/contrib/freenet-ext/tmp/wrapper_3.5.5_src/doc/index.html (No such file or directory)'.  Falling back to streams.

    BUILD FAILED
    /home/steve/freenet/contrib/freenet-ext/build.xml:216: The following error occurred while executing this line:
    /home/steve/freenet/contrib/freenet-ext/build.xml:298: The following error occurred while executing this line:
    /home/steve/freenet/contrib/freenet-ext/build.xml:316: Failed to copy /home/steve/freenet/contrib/freenet-ext/tmp/wrapper_3.5.5_src/doc/index.html to /home/steve/freenet/contrib/wrapper/doc/index.html due to /home/steve/freenet/contrib/freenet-ext/tmp/wrapper_3.5.5_src/doc/index.html (No such file or directory)

I'm running Ant 1.9.4.

**Comment by Thynix** [comment]
Any word on this?

**Comment by Thynix** [comment]
Closed for inactivity after review. If you'd like to reopen it please let me know.

**Pull request closed without merging**
